service: opensource-calendar-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

functions:
  list:
    handler: handler.list
    events:
      - http:
          path: events
          method: get
          cors: true
