service: osevents-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

plugins:
  - serverless-plugin-typescript 
  - serverless-offline
  - serverless-domain-manager # https://seed.run/blog/how-to-set-up-a-custom-domain-name-for-api-gateway-in-your-serverless-app.html

functions:
  list:
    handler: handler.list
    events:
      - http:
          path: events
          method: get
          cors: true
  crawl:
    handler: handler.crawl
    events:
      - schedule: rate(10080 minutes)
      - http:
          path: crawl
          method: get
          cors: true

custom:
  customDomain:
    domainName: api.osevents.io